# Use a Maven image to build the JAR
FROM maven:3.8.4-openjdk-17 AS build

# Set the working directory
WORKDIR /app

# Copy the project files to the container
COPY . .

# Run the Maven build
RUN mvn clean package

# Use an OpenJDK image to run the application
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/target/my-app-1.0-SNAPSHOT-jar-with-dependencies.jar my-app.jar

# Command to run the JAR file
ENTRYPOINT ["java", "-jar", "my-app.jar"]

